package com.example.demo.entity;

import java.util.Date;

public class Orders {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.id
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_no
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private String orderNo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.amount
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private Integer amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.status
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.remark
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.order_type
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private String orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.source
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private String source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.customer
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private String customer;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.created_at
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.updated_at
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.id
     *
     * @return the value of orders.id
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.id
     *
     * @param id the value for orders.id
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_no
     *
     * @return the value of orders.order_no
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public String getOrderNo() {
        return orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_no
     *
     * @param orderNo the value for orders.order_no
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.amount
     *
     * @return the value of orders.amount
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public Integer getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.amount
     *
     * @param amount the value for orders.amount
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.status
     *
     * @return the value of orders.status
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.status
     *
     * @param status the value for orders.status
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.remark
     *
     * @return the value of orders.remark
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.remark
     *
     * @param remark the value for orders.remark
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.order_type
     *
     * @return the value of orders.order_type
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public String getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.order_type
     *
     * @param orderType the value for orders.order_type
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setOrderType(String orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.source
     *
     * @return the value of orders.source
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.source
     *
     * @param source the value for orders.source
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setSource(String source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.customer
     *
     * @return the value of orders.customer
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public String getCustomer() {
        return customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.customer
     *
     * @param customer the value for orders.customer
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setCustomer(String customer) {
        this.customer = customer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.created_at
     *
     * @return the value of orders.created_at
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.created_at
     *
     * @param createdAt the value for orders.created_at
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.updated_at
     *
     * @return the value of orders.updated_at
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.updated_at
     *
     * @param updatedAt the value for orders.updated_at
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}