package com.example.demo.mapper;

import com.example.demo.entity.Orders;
import java.util.List;

public interface OrdersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    int insert(Orders row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    Orders selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    List<Orders> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Tue Feb 10 14:39:40 GMT+08:00 2026
     */
    int updateByPrimaryKey(Orders row);
}